### ISSUE TITLE
Privacy in python? Good luck!

### ISSUE THREAD

**Issue by bhavik-knight** [teamCandle/candle-light#9]
Add this in candle_test.py

```
# breaking the code
team.add(Person(None))

# THERE IS NO SUCH THINGS AS PRIVATE IN PYTHON
private = Person("Private")
team.add(private)
private._Person__name = "lol to privacy"
```

**Comment by MarlonJD** [comment]
I don't know about the subject but I saw this commit https://github.com/teamCandle/candle-python/commit/77040bd9e5aad9cb3941bfa13a8e81b0d78a0053

**Comment by bhavik-knight** [comment]
Hi @MarlonJD,

Why pull requests are kept getting merged to master? There can be bugs in everyone codes. First all bugs, issues need to be fixed. Check every corner-cases possible, fix major-minor bugs, with doc-strings, method names, etc.

If everything works fine for all involved members, then it should be merged to master!! Till then bugs are to be fixed in branches itself. And you gotta give some time to a member when you have some request, issues for a member who did that commit before merging anything!
----------

Another major issue! About emails -- how many of you can see my email? Because I can see some of yours. I'm not comfortable with having my email public, there is a reason in my settings I kept is as a private. But sometimes from the command line, it creates problems with pushing codes!

**Comment by majdbousaad** [comment]
> Add this in candle_test.py
> 
> ```
> # breaking the code
> team.add(Person(None))
> 
> # THERE IS NO SUCH THINGS AS PRIVATE IN PYTHON
> private = Person("Private")
> team.add(private)
> private._Person__name = "lol to privacy"
> ```

I know there is no privacy in Python, but this will do two things:
1. It tells the developers that this item should be treated as private.
2. it makes the changes on these items less likely to happen, since `object.__private` won't work.

**Comment by bhavik-knight** [comment]
Fixed the bug related to length!

**Comment by bhavik-knight** [comment]
@majdbousaad: Not all developers are ethicals. It takes a small vulnerability for a black-hat hacker to crack open the code! Those are the security-related issues with python!

Anyways. I've shown the way that could be break, there is no way around it I'm afraid. Not that I know of.

**Comment by MarlonJD** [comment]
Firstly we're practicing pull, push, pull request, merge. Please be patient about the code and coding style etc.
We have to make good readme or wiki for these after team work, we can work together with rules in a real project, As you know I'm also learning GitHub things, I can make mistake...

**Comment by bhavik-knight** [comment]
@MarlonJD:
Pull is a bit tricky for me. I try to do merge locally for practice!

To see email + every commits:
`git log`

**Comment by MarlonJD** [comment]
I'll check when I come back to PC

**Comment by bhavik-knight** [comment]
And I am reading pro-git.pdf downloaded from git official website. I've had very bad experiences with branching working on my personal projects. This is the first time I'm able to push my code to a branch on GitHub and succeded fetching branches as needed. Reading README.md along with that pdf.

And lol code style and all. Let's keep it in one branch only. Let it be unmerged. I even closed pull request for it python-dev.

We keep a branch to learn. And other branch to develope project. And when we are comfortable, we cam merge to master. How about that idea?

**Comment by MarlonJD** [comment]
Yes branching and merge things is not simply at all. We should be careful about he merging sort. You suggest commiting only to dev branch ?

**Comment by bhavik-knight** [comment]
I suggest

1. we keep one branch for practice (that is not master)

2. another branch for project-dev meanwhile (that is not master) (which we should not merge with master at the moment)

3. a master branch - linked with practice branch for merging - pull req, etc.
